language: node_js
node_js:
  - "8"
  - "6"
os:
  - linux
  - osx
cache:
  directories:
  - node_modules # NPM packages
  - typings # TypeScript Typings
script:
  - npm run lint
  # - npm test
notifications:
  email:
    on_success: never
    on_failure: change
