env:
  global:
    - CC_TEST_REPORTER_ID=647b2686eea1455308f41e70e10aa991c0f8e4c39ee20495d0247e6bbc738aa5
language: node_js
node_js:
  - "8"
  - "10"
os:
  - linux
  - osx
  - windows
cache:
  directories:
  - node_modules # NPM packages
before_script:
  - ./.travis-codeclimate.sh before
script:
  - npm install -g unibeautify @unibeautify/beautifier-eslint eslint@4
  - npm run lint
  - npm run build
  - npm test
after_script:
  - echo in after_script before the codeclimate command
  - ./.travis-codeclimate.sh after
  - echo in after_script after the codeclimate command
notifications:
  email:
    on_success: never
    on_failure: change
