environment:
  matrix:
    - nodejs_version: "8"
    - nodejs_version: "10"

install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm --version
  - npm install
  - npm install -g unibeautify @unibeautify/beautifier-eslint eslint@4

test_script:
  - npm test

# For Node projects, skip the default MSBuild-based build step.
build: off
